### ISSUE TITLE
Items in pinned section are not sticky

### ISSUE THREAD

**Issue by arneee** [consp1racy/material-navigation-drawer#6]
Hi,

I have the problem that items I add to the pinned section are not working as sticky items. As soon as I move the item to the normal section, they behave like intended.

**Comment by consp1racy** [comment]
Hello,

only items in main list can behave as sticky. This is by design and reflects behavior of Settings and Help items in Google apps which do not belong in standard app flow and their activities do not have a navigation menu. At the same time pinned section disappeared from the specs so current behavior of the library is unlikely to change in this regard.
